export const projects = [
  {
    id: "01",
    title: "Rural Classroom Connect",
    subtitle: "Digital Education Platform",
    period: "October’25 – December’25",
    description: "A full-stack education platform connecting rural classrooms.",
    detailDescription: "Rural Classroom Connect is a comprehensive full-stack education platform designed to bridge the gap between rural classrooms and quality educational resources. The application features a modern, intuitive interface that allows teachers and students to interact, access learning materials, and participate in virtual classes. Built with the MERN stack, it demonstrates proficiency in both frontend and backend development, with particular emphasis on user authentication, database optimization, and responsive design principles.",
    // points -> keyfeatures
    points: [
      "Implemented user authentication with secure login and registration functionality using JWT and bcrypt.",
      "Integrated real-time attendance tracking, allowing teachers to monitor student participation dynamically.",
      "Designed a mobile-responsive UI with React.js to ensure a seamless experience across different devices.",
      "Optimized MongoDB queries and indexing for faster and more efficient data retrieval, improving platform performance.",
      "Developed interactive virtual classroom features, enabling real-time communication and collaboration between teachers and students.",
      "using Socket.io and WebRTC for real-time messaging, notifications and video conferencing with low latency.",
      "Built a scalable backend with Node.js and Express.js, handling API requests, authentication, and data processing efficiently.",
    ],
    techStack: ["MongoDB", "Express.js", "React.js", "Node.js", "Socket.io", "WebRTC", "JWT", "bcrypt", "CSS"],
    image: "https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Full Stack",
    liveUrl: "/unavailable",
    githubUrl: "/unavailable",
  },
  {
    id: "02",
    title: "The Meme Lab 🤣",
    subtitle: "Meme Creation and Sharing Platform",
    period: "January’26 – February’26",
    description: "A web app for watching, creating and sharing memes.",
    detailDescription: "Meme Lab is an engaging web application that allows users to watch, create, customize, and share memes with ease. The platform features a user-friendly interface where users can select from a variety of meme templates, add their own text, and apply different styles to create humorous content and see trending memes. Built using HTML5, CSS, and JavaScript, Meme Lab showcases skills in full-stack development, including API design and integration and responsive design principles.",
    points: [
      "Developed a dynamic meme creation tool using HTML5 Canvas API, allowing users to customize meme templates with text and styles.",
      "Integrated backend API with JavaScript to handle meme storage, retrieval, and user interactions.",
      "Implemented responsive design techniques to ensure optimal user experience across various devices and screen sizes.",
      "Utilized local storage to save user-created memes, enabling easy access and sharing without server dependency.",
      "Incorporated social sharing features, allowing users to share their memes directly to popular social media platforms.",
    ],
    techStack: ["HTML5", "CSS3", "JavaScript", "Canvas API", "Reddit API", "Local Storage"],
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Full Stack",
    liveUrl: "https://thememelab.vercel.app/",
    githubUrl: "https://github.com/Vaibhav5860/meme-lab",
  },
  {
    id: "03",
    title: "projectHub",
    subtitle: "Project Management Tool",
    period: "February’26 – March’26",
    description: "A project management tool for teams to collaborate and track progress.",
    detailDescription: "ProjectHub is a comprehensive project management tool designed to facilitate team collaboration and progress tracking. The platform offers features such as task assignment, progress visualization, and real-time updates, enabling teams to manage their projects efficiently. Built with the MERN stack, ProjectHub demonstrates proficiency in both frontend and backend development, with a focus on user experience and performance optimization.",
    points: [
      "Implemented task management features, allowing users to create, assign, and track tasks and projects with real-time updates.",
      "Designed a responsive user interface using React.js, ensuring seamless access across various devices and screen sizes.",
      "Optimized backend performance with Node.js and Express.js, handling API requests and data processing efficiently.",
      "Integrated MongoDB (atlas) for robust data storage and retrieval, ensuring scalability and reliability of the application.",
      "Incorporated real-time collaboration features using Socket.io, enabling team members to communicate and update project status dynamically.",
    ],
    techStack: ["MongoDB", "Express.js", "React.js", "Node.js", "Socket.io"],
    image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Full Stack",
    liveUrl: "https://project-hub-web.vercel.app/",
    githubUrl: "https://github.com/Vaibhav5860/projectHub",

  },
  {
    id: "04",
    title: "Nexus OpenChat",
    subtitle: "Random Chat & Video Call Platform",
    period: "March'26",
    description: "A real-time web app to chat and video call with random people worldwide.",
    detailDescription: "NexusOpenChat is a real-time communication platform that connects strangers for text chat and video calls - similar to Omegle but with a modern, polished experience. Users are instantly matched with a random online peer and can switch to the next person at any time. The platform leverages WebRTC for peer-to-peer video streaming and Socket.io for low-latency signaling and text messaging, ensuring a smooth and responsive experience across devices.",
    points: [
      "Built peer-to-peer video calling using WebRTC with STUN/TURN server support for NAT traversal across different networks.",
      "Implemented real-time random matchmaking with Socket.io, pairing users instantly and handling disconnections gracefully.",
      "Developed a live text chat alongside the video stream, allowing users to send messages during the call.",
      "Added a 'Next' feature enabling users to skip the current peer and get matched with a new random user seamlessly.",
      "Designed a responsive, minimal UI that works across desktop and mobile browsers without any app installation.",
      "Handled edge cases like abrupt disconnections, empty queues, and camera/microphone permission failures gracefully.",
    ],
    techStack: ["React.js", "Node.js", "Express.js", "Socket.io", "WebRTC", "CSS", "STUN/TURN Servers"],
    image: "https://images.unsplash.com/photo-1611746872915-64382b5c76da?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Full Stack",
    liveUrl: "https://nexusopenchat.vercel.app",
    githubUrl: "https://github.com/Vaibhav5860/NexusChat",
  }
];